#!/bin/bash

# Creado por proyectoRpi 21/01/2014
# Script que registra las temperatruras del SoC de cada rpi del cluster

LOGPATH=/home/pi/logs/performance.log

echo -e "#####################################################\n" >> $LOGPATH

for i in $(cat /home/pi/.hosts2 | grep -v "#"); do
	echo $i >> $LOGPATH
	ssh $i "/opt/vc/bin/vcgencmd measure_temp && echo "freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq) Hz"" >> $LOGPATH
done
