#!/bin/bash

# Creado por proyectoRpi 20/01/2014
	
# Script para ejecutar tareas en cluster con openmpi
# Verificamos si el comando ha sido ejecutado con algun parametro
	
# Si hay parametro se valida	
while test $# -gt 0; do
	case "$1" in
	
		-v|--version)
			echo "runtask version 1.0"
			echo "Correr programas en el cluster Raspberry Pi"
			echo "Usando mpirun de openmpi"
			exit 0
			;;

		# Caso -p (numero de procesos)
		-p)
			shift
			if test $# -gt 0;
			then
				# Segundo, se corre el programa
				mpirun -np $1 -mca btl ^openib -hostfile machinefile $2
			else
				echo "Especifique cantidad de procesos."
				exit 1
			fi
			shift

			exit 0
			;;

		# en cualquier cotro caso se muestra el parametro invalido
		*)
			echo "Parametro invalido."
			echo "No se hace nada para $1."
			break
			;;
	esac
done
