#!/bin/bash

# Creado por proyectoRpi
# Script que registra las temperatruras del SoC de cada rpi del cluster

echo "#####################################################"

for i in {0..5..1}; do
	TEMP=$(ssh rpi0$i /opt/vc/bin/vcgencmd measure_temp)
	echo -e "rpi0$i: $TEMP" >> /home/pi/logs/SoCtemp
done

echo -e "\n"
